# Generated by Django 3.1.7 on 2021-02-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_convertedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfile',
            name='c_file',
            field=models.CharField(max_length=60),
        ),
    ]
