# Generated by Django 3.1.7 on 2021-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210226_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='convertedfile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fileconversion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
